/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Template } from "./Template";
import { TemplateCountArgs } from "./TemplateCountArgs";
import { TemplateFindManyArgs } from "./TemplateFindManyArgs";
import { TemplateFindUniqueArgs } from "./TemplateFindUniqueArgs";
import { CreateTemplateArgs } from "./CreateTemplateArgs";
import { UpdateTemplateArgs } from "./UpdateTemplateArgs";
import { DeleteTemplateArgs } from "./DeleteTemplateArgs";
import { GeneratedTemplateFindManyArgs } from "../../generatedTemplate/base/GeneratedTemplateFindManyArgs";
import { GeneratedTemplate } from "../../generatedTemplate/base/GeneratedTemplate";
import { Project } from "../../project/base/Project";
import { User } from "../../user/base/User";
import { TemplateService } from "../template.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Template)
export class TemplateResolverBase {
  constructor(
    protected readonly service: TemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "any",
  })
  async _templatesMeta(
    @graphql.Args() args: TemplateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Template])
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "any",
  })
  async templates(
    @graphql.Args() args: TemplateFindManyArgs
  ): Promise<Template[]> {
    return this.service.templates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Template, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "read",
    possession: "own",
  })
  async template(
    @graphql.Args() args: TemplateFindUniqueArgs
  ): Promise<Template | null> {
    const result = await this.service.template(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Template)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "create",
    possession: "any",
  })
  async createTemplate(
    @graphql.Args() args: CreateTemplateArgs
  ): Promise<Template> {
    return await this.service.createTemplate({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Template)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "update",
    possession: "any",
  })
  async updateTemplate(
    @graphql.Args() args: UpdateTemplateArgs
  ): Promise<Template | null> {
    try {
      return await this.service.updateTemplate({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Template)
  @nestAccessControl.UseRoles({
    resource: "Template",
    action: "delete",
    possession: "any",
  })
  async deleteTemplate(
    @graphql.Args() args: DeleteTemplateArgs
  ): Promise<Template | null> {
    try {
      return await this.service.deleteTemplate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Template)
  async uploadTemplateData(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: TemplateFindUniqueArgs
  ): Promise<Template> {
    return await this.service.uploadTemplateData(args, file);
  }

  @graphql.Mutation(() => Template)
  async deleteTemplateData(
    @graphql.Args()
    args: TemplateFindUniqueArgs
  ): Promise<Template> {
    return await this.service.deleteTemplateData(args);
  }

  @graphql.Mutation(() => Template)
  async uploadThumbnail(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: TemplateFindUniqueArgs
  ): Promise<Template> {
    return await this.service.uploadThumbnail(args, file);
  }

  @graphql.Mutation(() => Template)
  async deleteThumbnail(
    @graphql.Args()
    args: TemplateFindUniqueArgs
  ): Promise<Template> {
    return await this.service.deleteThumbnail(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [GeneratedTemplate], {
    name: "generatedTemplates",
  })
  @nestAccessControl.UseRoles({
    resource: "GeneratedTemplate",
    action: "read",
    possession: "any",
  })
  async findGeneratedTemplates(
    @graphql.Parent() parent: Template,
    @graphql.Args() args: GeneratedTemplateFindManyArgs
  ): Promise<GeneratedTemplate[]> {
    const results = await this.service.findGeneratedTemplates(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  @nestAccessControl.UseRoles({
    resource: "Project",
    action: "read",
    possession: "any",
  })
  async getProject(
    @graphql.Parent() parent: Template
  ): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Template): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
