/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DefaultTemplateService } from "../defaultTemplate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DefaultTemplateCreateInput } from "./DefaultTemplateCreateInput";
import { DefaultTemplate } from "./DefaultTemplate";
import { DefaultTemplateFindManyArgs } from "./DefaultTemplateFindManyArgs";
import { DefaultTemplateWhereUniqueInput } from "./DefaultTemplateWhereUniqueInput";
import { DefaultTemplateUpdateInput } from "./DefaultTemplateUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DefaultTemplateControllerBase {
  constructor(
    protected readonly service: DefaultTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DefaultTemplate })
  @nestAccessControl.UseRoles({
    resource: "DefaultTemplate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDefaultTemplate(
    @common.Body() data: DefaultTemplateCreateInput
  ): Promise<DefaultTemplate> {
    return await this.service.createDefaultTemplate({
      data: data,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        planName: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DefaultTemplate] })
  @ApiNestedQuery(DefaultTemplateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DefaultTemplate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async defaultTemplates(
    @common.Req() request: Request
  ): Promise<DefaultTemplate[]> {
    const args = plainToClass(DefaultTemplateFindManyArgs, request.query);
    return this.service.defaultTemplates({
      ...args,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        planName: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DefaultTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DefaultTemplate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async defaultTemplate(
    @common.Param() params: DefaultTemplateWhereUniqueInput
  ): Promise<DefaultTemplate | null> {
    const result = await this.service.defaultTemplate({
      where: params,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        planName: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DefaultTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DefaultTemplate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDefaultTemplate(
    @common.Param() params: DefaultTemplateWhereUniqueInput,
    @common.Body() data: DefaultTemplateUpdateInput
  ): Promise<DefaultTemplate | null> {
    try {
      return await this.service.updateDefaultTemplate({
        where: params,
        data: data,
        select: {
          createdAt: true,
          duration: true,
          id: true,
          planName: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DefaultTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DefaultTemplate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDefaultTemplate(
    @common.Param() params: DefaultTemplateWhereUniqueInput
  ): Promise<DefaultTemplate | null> {
    try {
      return await this.service.deleteDefaultTemplate({
        where: params,
        select: {
          createdAt: true,
          duration: true,
          id: true,
          planName: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
