/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Image as PrismaImage,
  User as PrismaUser,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class ImageServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.ImageCountArgs, "select">): Promise<number> {
    return this.prisma.image.count(args);
  }

  async images<T extends Prisma.ImageFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindManyArgs>
  ): Promise<PrismaImage[]> {
    return this.prisma.image.findMany<Prisma.ImageFindManyArgs>(args);
  }
  async image<T extends Prisma.ImageFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindUniqueArgs>
  ): Promise<PrismaImage | null> {
    return this.prisma.image.findUnique(args);
  }
  async createImage<T extends Prisma.ImageCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageCreateArgs>
  ): Promise<PrismaImage> {
    return this.prisma.image.create<T>(args);
  }
  async updateImage<T extends Prisma.ImageUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageUpdateArgs>
  ): Promise<PrismaImage> {
    return this.prisma.image.update<T>(args);
  }
  async deleteImage<T extends Prisma.ImageDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageDeleteArgs>
  ): Promise<PrismaImage> {
    return this.prisma.image.delete(args);
  }

  async uploadImageUrl<T extends Prisma.ImageFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaImage> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "imageUrl";
    const imageUrl = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.image.update({
      where: args.where,

      data: {
        imageUrl: imageUrl as InputJsonValue,
      },
    });
  }

  async downloadImageUrl<T extends Prisma.ImageFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindUniqueArgs>
  ): Promise<FileDownload> {
    const { imageUrl } = await this.prisma.image.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      imageUrl as unknown as LocalStorageFile
    );
  }

  async deleteImageUrl<T extends Prisma.ImageFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ImageFindUniqueArgs>
  ): Promise<PrismaImage> {
    const { imageUrl } = await this.prisma.image.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      imageUrl as unknown as LocalStorageFile
    );

    return await this.prisma.image.update({
      where: args.where,

      data: {
        imageUrl: Prisma.DbNull,
      },
    });
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.image
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
